FROM node:22-alpine

WORKDIR /app

# Set proxy for npm
ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}

# Optional: disable strict SSL if your proxy intercepts HTTPS
RUN npm config set strict-ssl false

# Install dependencies first (for caching)
COPY package*.json ./

# Optional: clean cache
RUN npm cache clean --force

# Install npm dependencies
RUN npm install

# Copy the rest of the source
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
